# Support Vector Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

### Printing matrix of features X and dependent variable y

In [4]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [5]:
print(y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


#### Reshape the dependent variable y

In [7]:
#y = y.reshape(len(y),1)
y= y.reshape(-1, 1)

Reshaping the dependent variable y into an array because we have to use standard scalar class that will perform standardization that means feature scaling expects one unique format in it's input. When we apply fit transform method which is a 2-D array, if you input here 1-D vector like that we have it will give us error simply because standard scalar class expects it's input to be 2-D aaray. So we have reshape it.

In [8]:
print(y)

[[192261.83]
 [191792.06]
 [191050.39]
 [182901.99]
 [166187.94]
 [156991.12]
 [156122.51]
 [155752.6 ]
 [152211.77]
 [149759.96]
 [146121.95]
 [144259.4 ]
 [141585.52]
 [134307.35]
 [132602.65]
 [129917.04]
 [126992.93]
 [125370.37]
 [124266.9 ]
 [122776.86]
 [118474.03]
 [111313.02]
 [110352.25]
 [108733.99]
 [108552.04]
 [107404.34]
 [105733.54]
 [105008.31]
 [103282.38]
 [101004.64]
 [ 99937.59]
 [ 97483.56]
 [ 97427.84]
 [ 96778.92]
 [ 96712.8 ]
 [ 96479.51]
 [ 90708.19]
 [ 89949.14]
 [ 81229.06]
 [ 81005.76]
 [ 78239.91]
 [ 77798.83]
 [ 71498.49]
 [ 69758.98]
 [ 65200.33]
 [ 64926.08]
 [ 49490.75]
 [ 42559.73]
 [ 35673.41]
 [ 14681.4 ]]


## Encoding categorical data

In [9]:
#we are dummy encoding as the machine learning algorithms will be
#confused with the values like New York > Florida > California

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

## Splitting the dataset into train set and test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
print(X_train)

[[0.0 1.0 0.0 55493.95 103057.49 214634.81]
 [0.0 0.0 1.0 46014.02 85047.44 205517.64]
 [0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [1.0 0.0 0.0 46426.07 157693.92 210797.67]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [0.0 0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [0.0 1.0 0.0 61994.48 115641.28 91131.24]
 [1.0 0.0 0.0 63408.86 129219.61 46085.25]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [1.0 0.0 0.0 23640.93 96189.63 148001.11]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 15505.73 127382.3 35534.17]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [1.0 0.0 0.0 64664.71 139553.16 137962.62]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [1.0 0.0 0.0 28754.33 118546.05 172795.67]
 [1.

In [13]:
print(X_test)

[[0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 0.0 1.0 61136.38 152701.92 88218.23]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]


In [14]:
print(y_train)

[[ 96778.92]
 [ 96479.51]
 [105733.54]
 [ 96712.8 ]
 [124266.9 ]
 [155752.6 ]
 [132602.65]
 [ 64926.08]
 [ 35673.41]
 [101004.64]
 [129917.04]
 [ 99937.59]
 [ 97427.84]
 [126992.93]
 [ 71498.49]
 [118474.03]
 [ 69758.98]
 [152211.77]
 [134307.35]
 [107404.34]
 [156991.12]
 [125370.37]
 [ 78239.91]
 [ 14681.4 ]
 [191792.06]
 [141585.52]
 [ 89949.14]
 [108552.04]
 [156122.51]
 [108733.99]
 [ 90708.19]
 [111313.02]
 [122776.86]
 [149759.96]
 [ 81005.76]
 [ 49490.75]
 [182901.99]
 [192261.83]
 [ 42559.73]
 [ 65200.33]]


In [15]:
print(y_test)

[[103282.38]
 [144259.4 ]
 [146121.95]
 [ 77798.83]
 [191050.39]
 [105008.31]
 [ 81229.06]
 [ 97483.56]
 [110352.25]
 [166187.94]]


## Feature Scaling

In [21]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:].astype(float))
X_test[:,3:]=sc.transform(X_test[:,3:].astype(float))
y_train[:,:]=sc.fit_transform(y_train[:,:].astype(float))
y_test[:,:]=sc.fit_transform(y_test[:,:].astype(float))

In [22]:
print(X_train)

[[0.0 1.0 0.0 -0.3500645436227846 -0.785471092479328 0.1011968019362537]
 [0.0 0.0 1.0 -0.5553031874263143 -1.481174262628152 0.027349791742770867]
 [0.0 1.0 0.0 0.0793576230758627 0.8013338146656691 -0.551521323997471]
 [1.0 0.0 0.0 -0.5463823849331266 1.3250581707161826 0.07011683779235596]
 [0.0 1.0 0.0 0.4348537132854594 -0.35598663482009574 0.7514851578736045]
 [0.0 1.0 0.0 1.2694314288195354 0.8551851851749717 0.9860311844743817]
 [0.0 1.0 0.0 1.045250070905001 1.28077047109427 0.44039999942558467]
 [0.0 0.0 1.0 -1.5298430007009785 0.02942064913343872 -1.6218751012780779]
 [0.0 0.0 1.0 -1.5397625087372087 -2.7676726417306963 -1.6372965026688249]
 [0.0 0.0 1.0 -0.13115188245559198 1.1449770059892659 -0.7694999122824162]
 [0.0 0.0 1.0 0.9279161337222449 -0.029920619212991245 0.4830316172654912]
 [0.0 1.0 0.0 -0.20932933131592577 -0.2993767953792611
  -0.8991541175619613]
 [1.0 0.0 0.0 -0.17870827894287705 0.22513519799815207 -1.264016424912327]
 [1.0 0.0 0.0 0.1374708978830804 -0.0

In [23]:
print(X_test)

[[0.0 1.0 0.0 -0.12149520306216517 2.288905303201222 -0.6803228661410794]
 [1.0 0.0 0.0 0.6280306007656554 -1.2206949887864669 0.3855777367735483]
 [0.0 1.0 0.0 0.6549006077802046 -0.49434194923946895 0.21885524294941483]
 [0.0 1.0 0.0 -0.9476214838934973 -1.494179356244994 -0.30512103616996794]
 [0.0 1.0 0.0 1.770481112122021 -0.8593266741758998 1.6668807950731055]
 [0.0 0.0 1.0 0.009617753042540284 0.17279111579172496 1.223412293727772]
 [0.0 0.0 1.0 -1.1135310904221218 -2.2189617565712103
  -0.13669119113063424]
 [0.0 0.0 1.0 -0.22790702970059842 1.1322241571857965 -0.9227488382004619]
 [0.0 1.0 0.0 0.050470070655803966 -0.023511746780133267
  0.8195207427154027]
 [0.0 1.0 0.0 1.5250985323520592 -1.2361016229924884 1.3285846911963286]]


In [24]:
print(y_train)

[[-0.31304376]
 [-0.32044287]
 [-0.09175449]
 [-0.31467774]
 [ 0.3662475 ]
 [ 1.14433163]
 [ 0.57224308]
 [-1.10020076]
 [-1.82310158]
 [-0.20861649]
 [ 0.50587547]
 [-0.23498575]
 [-0.29700745]
 [ 0.43361398]
 [-0.93778138]
 [ 0.22309235]
 [-0.98076868]
 [ 1.05682957]
 [ 0.61437014]
 [-0.05046517]
 [ 1.17493831]
 [ 0.39351679]
 [-0.77118537]
 [-2.34186247]
 [ 2.03494965]
 [ 0.79423047]
 [-0.48182335]
 [-0.02210286]
 [ 1.15347296]
 [-0.01760646]
 [-0.46306547]
 [ 0.04612731]
 [ 0.32942519]
 [ 0.9962397 ]
 [-0.70283485]
 [-1.4816433 ]
 [ 1.81525556]
 [ 2.04655875]
 [-1.65292476]
 [-1.09342341]]


In [25]:
print(y_test)

[[-0.53115717]
 [ 0.61468158]
 [ 0.66676399]
 [-1.24375265]
 [ 1.92309614]
 [-0.48289506]
 [-1.14783326]
 [-0.69330934]
 [-0.33346268]
 [ 1.22786846]]


## Training the Support Vector Regression model on the Training set

In [29]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf',gamma='auto')
regressor.fit(X_train,np.ravel(y_train,order='C'))

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

 ## Accuracy of train model

In [30]:
print(f'r_square value: {regressor.score(X_train, y_train)}')

r_square value: 0.9429386796823852


## Predicting the test set results

In [31]:
y_pred = regressor.predict(X_test)

## Accuracy of test model

In [32]:
print(f'r_square value: {regressor.score(X_test, y_test)}')

r_square value: 0.7359882509043087


From the test set results we can see that our model is approximately 74% accurate.

In [ ]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[6.5]])))